version: '3'
services:
  ros-master:
    image: gramaziokohler/ros-base
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-base
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-base
    container_name: ros-fileserver
    environment:
      - "ROS_HOSTNAME=ros-fileserver"
      - "ROS_MASTER_URI=http://ros-master:11311"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  ros-moveit-base:
    image: gramaziokohler/ros-moveit-base
    container_name: ros-moveit-base
    environment:
      - "DISPLAY=docker.for.win.localhost:0.0"
      # - "DISPLAY=docker.for.mac.localhost:0.0"   (swap this with the previous line if on Mac)
      - "ROS_HOSTNAME=ros-moveit-base"
      - "ROS_MASTER_URI=http://ros-master:11311"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - panda_moveit_config
      - demo.launch
      - rviz_tutorial:=true
